Fix merge issues

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,7 +2,7 @@
 
 # Usage:
 #
-#     $ bin/compile <build-dir> <cache-dir>
+# $ bin/compile <build-dir> <cache-dir>
 
 
 # Fail fast and fail hard.
@@ -67,13 +67,13 @@ source $BIN_DIR/steps/hooks/pre_compile
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
-  puts-step "No requirements.txt provided; assuming dist package."
+puts-step "No requirements.txt provided; assuming dist package."
   echo "-e ." > requirements.txt
 fi
 
 # If no runtime given, assume default version.
 if [ ! -f runtime.txt ]; then
-  puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
+puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
   echo $DEFAULT_PYTHON_VERSION > runtime.txt
 fi
 
@@ -86,7 +86,7 @@ mkdir -p $CACHE_DIR
 
 # Restore old artifacts from the cache.
 for dir in $CACHED_DIRS; do
-  cp -R $CACHE_DIR/$dir . &> /dev/null || true
+cp -R $CACHE_DIR/$dir . &> /dev/null || true
 done
 
 set +e
@@ -101,24 +101,24 @@ PYTHON_VERSION=$(cat runtime.txt)
 
 # Install Python.
 if [ -f .heroku/python-version ]; then
-  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
-    puts-step "Found $(cat .heroku/python-version), removing."
+if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
+puts-step "Found $(cat .heroku/python-version), removing."
     rm -fr .heroku/python
   else
-    SKIP_INSTALL=1
+SKIP_INSTALL=1
   fi
 fi
 
 
 if [ ! "$SKIP_INSTALL" ]; then
-  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+puts-step "Preparing Python runtime ($PYTHON_VERSION)"
   curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
   if [[ $? != 0 ]] ; then
-    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
-    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+    puts-warn "Aborting. More info: https://devcenter.heroku.com/articles/python-support"
     exit 1
   fi
-  mv python .heroku/python
+mv python .heroku/python
 
   # Record for future reference.
   echo $PYTHON_VERSION > .heroku/python-version
@@ -127,17 +127,17 @@ if [ ! "$SKIP_INSTALL" ]; then
   # Prepare it for the real world
   puts-step "Installing Distribute (0.6.34)"
   cd $ROOT_DIR/vendor/distribute-0.6.34/
-  python setup.py install  &> /dev/null
+  python setup.py install &> /dev/null
   cd $WORKING_DIR
 
   puts-step "Installing Pip (1.2.1)"
   cd $ROOT_DIR/vendor/pip-1.2.1/
-  python setup.py install  &> /dev/null
+  python setup.py install &> /dev/null
   cd $WORKING_DIR
 
   hash -r
 else
-  puts-step "Using Python runtime ($PYTHON_VERSION)"
+puts-step "Using Python runtime ($PYTHON_VERSION)"
 fi
 
 set -e
@@ -148,17 +148,10 @@ source $BIN_DIR/steps/pylibmc
 
 # Install Mercurial if it appears to be required.
 if (grep -Fiq "hg+" requirements.txt) then
-  pip install --use-mirrors mercurial | cleanup | indent
+pip install --use-mirrors mercurial | cleanup | indent
 fi
 
-# Install libspotify
-puts-step "Install libspotify"
-git clone https://github.com/khamaileon/libspotify.git
-cd libspotify
-mkdir -p $BUILD_DIR/.heroku/libspotify
-make install prefix=$BUILD_DIR/.heroku/libspotify
-cd ..
-rm -r libspotify
+
 
 # Install dependencies with Pip.
 puts-step "Installing dependencies using Pip (1.2.1)"
@@ -172,24 +165,18 @@ source $BIN_DIR/steps/collectstatic
 
 # Store new artifacts in cache.
 for dir in $CACHED_DIRS; do
-  rm -rf $CACHE_DIR/$dir
+rm -rf $CACHE_DIR/$dir
   cp -R $dir $CACHE_DIR/
 done
 
 # Set context environment variables.
-<<<<<<< HEAD
-
-set-env PATH '$HOME/.heroku/venv/bin:$PATH'
-set-default-env PYTHONUNBUFFERED true
-set-default-env LIBRARY_PATH /app/.heroku/vendor/lib:/app/.heroku/libspotify/lib
-set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib:/app/.heroku/libspotify/lib
-=======
 set-env PATH '$HOME/.heroku/python/bin:$PATH'
 set-env PYTHONUNBUFFERED true
 set-env PYTHONHOME /app/.heroku/python
 set-default-env LIBRARY_PATH /app/.heroku/vendor/lib
 set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib
->>>>>>> upstream/master
+set-default-env LIBRARY_PATH /app/.heroku/vendor/lib:/app/.heroku/libspotify/lib
+set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib:/app/.heroku/libspotify/lib
 set-default-env LANG en_US.UTF-8
 set-default-env PYTHONHASHSEED random
 set-default-env PYTHONPATH /app/
